### ISSUE TITLE
gives error

### ISSUE THREAD

**Issue by djpie123** [promosis/file-upload-with-preview#42]
ReferenceError: Element is not defined
    at /home/runner/aurora/node_modules/file-upload-with-preview/dist/file-upload-with-preview.umd.js:854:2
    at /home/runner/aurora/node_modules/file-upload-with-preview/dist/file-upload-with-preview.umd.js:2:82
    at Object.<anonymous> (/home/runner/aurora/node_modules/file-upload-with-preview/dist/file-upload-with-preview.umd.js:5:2)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at /home/runner/aurora/index.js:4:31
    at Script.runInContext (vm.js:130:18)

**Comment by johndatserakis** [comment]
Hi there, sorry you're having trouble. I'm not familiar with the error you posted. Could you share more information and perhaps show the error in an online code editor?

Here is a [link](https://codesandbox.io/s/file-upload-with-preview-4-2-0-86hib?file=/src/index.js) to a CodeSandbox I just made it using the newest version (4.2.0) of `file-upload-with-preview` and everything is working without issue. So perhaps it's a setting inside your project that is causing the error. Let me know.

**Comment by johndatserakis** [comment]
Closing, will reopen if needed.
